version: '3.9'

services:
  wiremock:
    image: wiremock/wiremock:2.32.0
    container_name: wiremock-feira-connect
    volumes:
      - ./wiremock:/home/wiremock
    ports:
      - 8080:8080
    command: --enable-stub-cors