/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CityCityImport } from './routes/city.$city'
import { Route as CityCityFarmerMarketImport } from './routes/city._$city.$farmerMarket'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CityCityRoute = CityCityImport.update({
  path: '/city/$city',
  getParentRoute: () => rootRoute,
} as any)

const CityCityFarmerMarketRoute = CityCityFarmerMarketImport.update({
  path: '/city/$city/$farmerMarket',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/city/$city': {
      preLoaderRoute: typeof CityCityImport
      parentRoute: typeof rootRoute
    }
    '/city/_$city/$farmerMarket': {
      preLoaderRoute: typeof CityCityFarmerMarketImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CityCityRoute,
  CityCityFarmerMarketRoute,
])

/* prettier-ignore-end */
